SAMPLES: ["A001_16"]
fastqPath: /mnt/lustre/groups/projectmine/testRNAseq/fastq/
outPath: /mnt/lustre/groups/projectmine/testRNAseq/output/
ref_hg38: /mnt/lustre/groups/herv_project/UCSC_hg38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
dataset_name: my_sample_data
ref: ref
resources: resources/
scripts: scripts
ERVmapBed: /mnt/lustre/groups/herv_project/ERVmap/ERVmap.bed
genomeDir: /mnt/lustre/groups/herv_project/UCSC_hg38/genome 
gtf: /mnt/lustre/groups/herv_project/UCSC_hg38/Homo_sapiens.GRCh38.104.gtf
